DefaultContentLanguage = "en"
author = "Red"
baseURL = "https://gohugo.io/"
copyright = "Copyleft © 2020"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "The Itoopietian"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "contact-us"
name = "Contact Us"
url = "/contact-us/"
weight = 20
[[menu.main]]
identifier = "donate"
name = "Donate"
url = "/donate/"
weight = 30
[params]
description = "An I2P Community Paper"
facebook = ""
github = ""
logo = "/images/ghost-transparent.png"
mainSections = ["post"]
twitter = ""
[privacy.instagram]
disabled = true
simple = true
[privacy.twitter]
disabled = true
enableDNT = true
simple = true
[privacy.vimeo]
disabled = true
simple = true
[privacy.youtube]
disabled = true
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
