DefaultContentLanguage = "en"
author = "Red"
baseURL = "https://gohugo.io/"
copyright = "Copyleft © 2020"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "The Itoopietian"
[[menu.main]]
identifier = "author"
name = "Author Homepage"
url = "https://jonathanjanssens.com"
weight = 4
[[menu.main]]
identifier = "github-repo-theme"
name = "Get Theme on Github"
url = "https://github.com/jonathanjanssens/hugo-casper3"
weight = 3
[[menu.main]]
identifier = "image-credit"
name = "Image Credit"
url = "/image-credit/"
weight = 2
[params]
description = "An I2P Community Paper"
facebook = ""
github = ""
logo = "/images/ghost-transparent.png"
mainSections = ["post"]
twitter = ""
[privacy.instagram]
disabled = true
simple = true
[privacy.twitter]
disabled = true
enableDNT = true
simple = true
[privacy.vimeo]
disabled = true
simple = true
[privacy.youtube]
disabled = true
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
